name: Publish to GitHub Packages

on:
  push:
    tags:
      - "v*.*.*" # Triggers on version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Required to publish packages

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies (if any)
        run: npm ci || npm install

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
